Was causing errors for my commit. So changed raw_input to input
1s
Run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.0/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.0/x64/lib
./Python/Day-of-the-Programmer.py:37:16: F821 undefined name 'raw_input'
    year = int(raw_input().strip())
               ^
1     F821 undefined name 'raw_input'
1
Error: Process completed with exit code 1.